// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFkRxSPEfArZl-KeOMEKKuQ44N1-YxPb4',
    appId: '1:315536156856:web:58381659f993c3cb2e2c4d',
    messagingSenderId: '315536156856',
    projectId: 'mops-ac848',
    authDomain: 'mops-ac848.firebaseapp.com',
    databaseURL: 'https://mops-ac848-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mops-ac848.appspot.com',
    measurementId: 'G-7PL763RX0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCorWICN5KUacWTSVetesMiyXrsQ4UsCKI',
    appId: '1:315536156856:android:4bc40fa127963b8f2e2c4d',
    messagingSenderId: '315536156856',
    projectId: 'mops-ac848',
    databaseURL: 'https://mops-ac848-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mops-ac848.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0YG1-KEbt2tWT0krsvBqo3Up2Y_pR0FQ',
    appId: '1:315536156856:ios:4fe36dcc179613ac2e2c4d',
    messagingSenderId: '315536156856',
    projectId: 'mops-ac848',
    databaseURL: 'https://mops-ac848-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mops-ac848.appspot.com',
    androidClientId: '315536156856-72bsal6mdtqrtod16jrbkdj8335t4h9l.apps.googleusercontent.com',
    iosClientId: '315536156856-edu9k2e7bsf9a0b1fqm1qfc4f8ti4edb.apps.googleusercontent.com',
    iosBundleId: 'com.mops.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0YG1-KEbt2tWT0krsvBqo3Up2Y_pR0FQ',
    appId: '1:315536156856:ios:86d3d642ed24b1382e2c4d',
    messagingSenderId: '315536156856',
    projectId: 'mops-ac848',
    databaseURL: 'https://mops-ac848-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mops-ac848.appspot.com',
    androidClientId: '315536156856-72bsal6mdtqrtod16jrbkdj8335t4h9l.apps.googleusercontent.com',
    iosClientId: '315536156856-vik0itqfdikpmk1jnjvhld6v9gqhaiaa.apps.googleusercontent.com',
    iosBundleId: 'com.mops.pos.RunnerTests',
  );
}
